# Generated by Django 3.2.15 on 2023-01-16 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('topic_display_name', models.CharField(max_length=1000)),
                ('topic_identifier', models.CharField(max_length=1000, null=True)),
                ('topic_html_page', models.CharField(max_length=1000, null=True)),
                ('topic_slug', models.SlugField(max_length=1000, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article_name', models.CharField(max_length=1000, null=True)),
                ('article_title', models.CharField(max_length=1000, null=True)),
                ('article_content', models.TextField()),
                ('article_author', models.CharField(max_length=1000, null=True)),
                ('article_identifier', models.CharField(max_length=1000, null=True)),
                ('article_html_page', models.CharField(max_length=1000, null=True)),
                ('article_html_page_path', models.CharField(max_length=1000, null=True)),
                ('article_slug', models.SlugField(max_length=1000, null=True, unique=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('article_topic', models.ForeignKey(default='no_topic', on_delete=django.db.models.deletion.SET_DEFAULT, to='article_app.topic')),
            ],
        ),
    ]
