# Generated by Django 3.2.15 on 2023-01-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='media/'),
        ),
    ]
